### ISSUE TITLE
..

### ISSUE THREAD

**Issue by aiweisir** [yz124/superstar#1]
.....

**Comment by yz124** [comment]
不明白具体所指，还请明示~

**Comment by river291** [comment]
NewStarService()这个service里面的这个函数声明了没有调用，还能实例话dao这个结构变量么？这里不是很理解，请老师指示。

**Comment by yz124** [comment]
@river291 不经过service实例化dao也是可以的，正常调用方法，正确传参数进去就可以 dao.NewSuperstarDao(datasource.InstanceMaster()
