### ISSUE TITLE
iris的websocket类缺少ConnectionFunc,Config,OnConnection？怎么办？

### ISSUE THREAD

**Issue by czl0325** [yz124/superstar#3]
在你的bootstrapper.go文件中，目前的iris的websocket类没有ConnectionFunc,Config,OnConnection这些参数了。

<img width="689" alt="image" src="https://user-images.githubusercontent.com/2100549/63250999-6f099b80-c29f-11e9-8b09-0433cec2c395.png">

和解？包都引入了！

<img width="571" alt="image" src="https://user-images.githubusercontent.com/2100549/63251049-85175c00-c29f-11e9-8e47-460192e92491.png">

**Comment by yz124** [comment]
可能是 iris 有升级更新，方法、参数变了吧，需要跟进修复下了

**Comment by czl0325** [comment]
麻烦把修复结果告知下

**Comment by gawinwu** [comment]
貌似还没有修复好
